### PR TITLE
Add Lo-Fi's to version control folder

### PR DESCRIPTION
**Pull request by MikaelFeher**
PT Story: https://www.pivotaltracker.com/story/show/127529147

Changes proposed in this pull request:
- Adding the Lo-Fi's to the main project folder

@diraulo @tochman - This PR is ready for review

### CODE REVIEW

**Comment by tochman** [comment]
You need to add /coverage/\* to .gitignore

**Comment by tochman** [comment]
And clean it from cache in git

**Comment by MikaelFeher** [comment]
Will do

**Comment by MikaelFeher** [comment]
@tochman Coverage removed from cache and it was already in the `.gitignore` file

**Comment by MikaelFeher** [comment]
@tochman Now the .gitignore should be properly updated.

**Pull request merged**
